name: path_finding
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^12.1.0
  json_annotation: ^4.8.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1

  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  gap: ^3.0.1
  intl: ^0.19.0

  flextras: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.14
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true



























