name: path_finding
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Intl
  intl: ^0.19.0

  #RestAPI
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  #Models
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5

  #Navigation
  go_router: ^14.6.2

  #State management(BLOC)
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Utils
  flutter_keyboard_visibility: ^6.0.0

  #Other
  gap: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.14
  json_serializable: ^6.8.0



flutter:

  uses-material-design: true



























